version: '3.8'

volumes:
  pgdata:

services:
  database:
    image: postgres:15.5-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    network_mode: host
    restart: always